### ISSUE TITLE
mzipWith that returns a default value on mismatch

### ISSUE THREAD

**Issue by Lysxia** [sjoerdvisscher/one-liner#10]
Currently `mzipWith` returns `mempty` if the constructors don't match, but then it is not possible to distinguish that case because `mempty` can also be the result of matching constructors (e.g., if all fields are zipped to `mempty`, in particular that is the case with nullary constructors). What do you think of adding

    mzipWith' :: ... => m -> (... => s -> s -> m) -> t -> t -> m

We can already do a comparison on `ctorIndex` beforehand, in fact, as the example on `mzipWith` demonstrates. That is actually more general because you can use the ordering between constructors but adds cruft if you only need to know whether they matched (the typical use case in a unification algorithm).

**Comment by Lysxia** [comment]
Same question for

    zipWithA' :: (Applicative f, ...) => f t -> (... => s -> s -> f s) -> t -> t -> f t

The reason this is more general than `Alternative` is that `empty` must be a recoverable error, and there is also the indistinguishability from the case where the constructors match but one field zips to `empty`.

**Comment by sjoerdvisscher** [comment]
If I remember correctly you can already do this by using Maybe m instead of m, right?

**Comment by Lysxia** [comment]
You get `Nothing` both when there is a mismatch and when there is a match with nullary constructors.

**Comment by sjoerdvisscher** [comment]
Dont you get Just (nullary constructor) in that case?
Op za 23 dec. 2017 om 17:44 schreef Xia Li-yao <notifications@github.com>

**Comment by Lysxia** [comment]
Hm, with `zipWithA` that would be the result. I really want the unifier (as a list of bindings), so I could use `WriterT [(Var, Term)] Maybe Term` but the returned term doesn't make much sense (for example, unifying `(a -> b)` with `((b -> d) -> (c -> d))` should result in `((c -> d) -> d) -> (c -> d)` but I need to go through a non-local operation to get there).

I still think `mzipWith` is too specialized and that small generalization would make it a lot more useful. Otherwise, every time we want to do something different in case of mismatch, we need to turn to `zipWithA`, and wrap/unwrap the relevant monoid in an applicative functor ignoring the `s` and `t` types in the result.

**Comment by sjoerdvisscher** [comment]
What about using `Endo m`? Then

    mZipWith' f = appEndo .: mZipWith (Endo .: (<>) .: f)

I think?

**Comment by Lysxia** [comment]
The last argument gets `mappend`-ed to the result if it matches an non-nullary constructor, or is returned as is for a nullary constructor.

    > let mzipWith' f = appEndo .: mzipWith @((~) ()) (Endo .: ((<>) .: f)) in
    > mzipWith' (\_ _ -> ".") (Just ()) (Just ()) "no match"  -- expected: "."
    ".no match"
    > mzipWith' (\_ _ -> ".") Nothing Nothing "no match"  -- expected: ""
    "no match"

**Comment by sjoerdvisscher** [comment]
Thanks for the suggestion and discussion!

**Comment by Lysxia** [comment]
You're welcome! Thanks for the update!
