### ISSUE TITLE
A place for default methods for common typeclasses?

### ISSUE THREAD

**Issue by mstksg** [sjoerdvisscher/one-liner#11]
Thanks for the great library!

I was actually writing a library of my own, but this library probably would have made my life a lot nicer had I discovered it in time :)  The library I started was https://github.com/mstksg/generics-lift (not yet released), and there is definitely a lot of overlap with *one-liner*.  I'd like to drop my package and use *one-liner* for everything, but I was wondering if you saw a place within *one-liner* for default methods for common typeclasses, like:

```haskell
genericMappend= binaryOp @Monoid mappend
genericPlus = binaryOp @Num (+)
```

These would be pretty useful for me, and was the original reason I set out to write *generics-lift* in the first place.  See https://mstksg.github.io/generics-lift/Data-Monoid-Generics.html

I'm hesitant to upload a package to hackage with such similar functionality to a great one that's already on it.  So, was wondering if you thought it might make sense to:

* Add `genericMappend`, `genericPlus`, etc. to as convenience modules in *one-liner* 
* Have a different package, *one-liner-instances*, that would provide default methods for common typeclasses

If you think these might make sense, I'd be willing to help with either of these! :)  However, if you feel like both of these are beyond the scope of *one-liner* and its ecosystem, I'd definitely understand, too!

**Comment by sjoerdvisscher** [comment]
Thanks! And sad to hear you didn't know about this package earlier. How did you find out about it eventually?

I think `one-liner-instances` is a great idea! It's fine by me if you want to go ahead and create it, I'd prefer not to be the main maintainer of yet another package.

**Comment by mstksg** [comment]
I think I did a few searches on hackage but the one that finally brought this one up was "generics numeric".  Hackage search isn't too great anyway, so I always feel like I've achieved a minor miracle whenever I find something through it :)

**Comment by mstksg** [comment]
Thanks for the blessing, put one up on Hackage! http://hackage.haskell.org/package/one-liner-instances

Was a quick one, but let me know if there's any notes you might have!  Thank you for the prompt reply earlier as well :)

**Comment by sjoerdvisscher** [comment]
Nice, that was fast! If you want to do more, `Ord` and `Bounded` have generic implementations too, you can find them in the documentation.

**Comment by mstksg** [comment]
Thanks for the tip!  Will add them in.  Thanks for the great library, and the spotlight too, btw!
