### ISSUE TITLE
Very big space leak when mapping over a big tree

### ISSUE THREAD

**Issue by mpickering** [sjoerdvisscher/one-liner#12]
https://gist.github.com/30ca5971d0f6bbeb38b1d388a23bedb4

Compiling the above example shows that the library allocates about 20x more than a hand written example.

```
Case      Allocated  GCs
small   958,560,632  922
smallH   45,612,912   43
```

The bigger example causes my computer to start swapping.

**Comment by sjoerdvisscher** [comment]
Hmm interesting! Do you get the same memory usage with `mapTree f  = gmap1 @Functor fmap f` instead of `tinmap`? (You need to derive `Generic1` too then)

**Comment by mpickering** [comment]
I tried other examples where the data type is not parametrised (so `Generic1` is not appropriate) and the same happens.

**Comment by sjoerdvisscher** [comment]
I understand, but if you could try it out it would show if the leak is in the library or in the example code.

**Comment by sjoerdvisscher** [comment]
I found the problem, the code isn't inlined enough. If you add `{-# INLINE tinplate #-}` and `{-# INLINE tinmap #-}`, and compile with `-O`, the allocations are equal:

```
Case     Allocated  GCs
small   44,041,560   42
smallH  44,041,584   42
```

I'll fix the example. And thanks for showing me the `weigh` package, that's really useful!
