### ISSUE TITLE
Metadata support

### ISSUE THREAD

**Issue by ocharles** [sjoerdvisscher/one-liner#14]
From what I can understand, `one-liner` operates without access to any metadata. Are there any ways to get access to metadata? I'm thinking of something like converting arbitrary `Generic` records into JSON records.

**Comment by sjoerdvisscher** [comment]
I've never considered `one-liner` to be the be-all and end-all of generics programming. Metadata also doesn't fit the "operate on the whole structure, given what to do for the leaves" shape.

But I'm thinking that maybe I could add a profunctor-transformer that adds the possibility to handle the `M1` nodes.

**Comment by ocharles** [comment]
That's perfectly reasonable. Rather than add more to your plate, I'm going to go ahead and close this as I used a different approach and no longer need this feature.
