### ISSUE TITLE
Use TH to further reduce standalone deriving ceremony

### ISSUE THREAD

**Issue by yairchu** [sjoerdvisscher/one-liner#16]
I've created [some TH](https://github.com/lamdu/syntax-tree/blob/master/src/Generics/OneLiner/TH.hs) to generate the

```Haskell
deriving instance Constraints (T a) A => A (T a)
instance Constraints (T a) B => B (T a)
```

boiler-plate via

```Haskell
makeDeriving ''A ''T
makeInstance ''B ''T
```

On its own it replaces one one-liner with another, but the strength of it is that if one derives the same instances to all the different types in their library, they can use this to create a single `makeCommonInstances` helper which replaces several deriving lines with a single simple line.
This helped me [remove many lines of boiler-plate](https://github.com/lamdu/syntax-tree/commit/399c61cb8c01f65a3cc91928d2ef61d996065e52) in my own code.

Do you think this is a good idea to have in one-liner? If so shall I create a PR for this?

**Comment by sjoerdvisscher** [comment]
Oh nice, I never realised you could use the Constraints type class this way!
Maybe it would be nice to have `makeDerivings` and `makeInstances` too which take a list of class names?

I see you're using the Constraints part only. You could also make a new package that takes that part out, and then I'll let one-liner depend on it.

**Comment by yairchu** [comment]
> Maybe it would be nice to have makeDerivings and makeInstances too which take a list of class names?

Sure, good idea!

> I see you're using the Constraints part only. You could also make a new package that takes that part out, and then I'll let one-liner depend on it.

How would you call it? `one-liner-constraints`? `generic-constraints`?

**Comment by sjoerdvisscher** [comment]
`generic-constraints`, afaict there's nothing specific to one-liner about it.

**Comment by yairchu** [comment]
> Oh nice, I never realised you could use the Constraints type class this way!
Maybe it would be nice to have makeDerivings and makeInstances too which take a list of class names?

And btw I learned this method from [this post](https://reasonablypolymorphic.com/blog/hkd-not-terrible/) by @isovector which shows

    deriving instance (Constraints (Person' f) Eq) => Eq (Person' f)

> generic-constraints, afaict there's nothing specific to one-liner about it.

On it!
So will do the extraction as a fork of `one-liner`, and call the module `Generics.Constraints`?

**Comment by yairchu** [comment]
I noticed that for the new library's needs, the `Constraints'` type family can be simplified - https://github.com/yairchu/generic-constraints/commit/b896e876b5e4325da23eec553113c66aad90a395

However in one-liner you do use its other features.

Would you want the new library to expose the original type family for one-liner's use? If so, how would we describe it?

**Comment by yairchu** [comment]
Uploaded the package - http://hackage.haskell.org/package/generic-constraints

Will now also add the new TH part to it.

**Comment by sjoerdvisscher** [comment]
This way I can't let one-liner depend on generic-constraints, but I agree that 6 versions is a bit much if you don't need them.

Could you add a line in the readme perhaps to say that this originally came from one-liner?

**Comment by yairchu** [comment]
> Could you add a line in the readme perhaps to say that this originally came from one-liner?

[Sure thing!](https://github.com/yairchu/generic-constraints#credits).

And btw of course I wrote you and Xia as the authors. Thanks!
