### ISSUE TITLE
`Constraints t AnyType` constraints

### ISSUE THREAD

**Issue by Lysxia** [sjoerdvisscher/one-liner#2]
Is there a reason for [these constraints](https://github.com/sjoerdvisscher/one-liner/blob/master/src/Generics/OneLiner/Internal.hs#L277-L290)? For example:

    type ADTRecord t = (Generic t, ADTRecord' (Rep t), Constraints t AnyType)

Doesn't `Constraints t AnyType` always hold?

**Comment by sjoerdvisscher** [comment]
It does, but GHC doesn't know it!

**Comment by Lysxia** [comment]
But the exported functions already expect a `Constraints t c` which is what `generic'`, `nonEmpty'`, `record'` require.

**Comment by sjoerdvisscher** [comment]
This way you can just require `ADT t` for a function that uses `For :: For AnyType`. See `ctorIndex` as an example.

**Comment by Lysxia** [comment]
I see. This seems to be a matter of taste then. Thanks for the discussion!
