### ISSUE TITLE
Unify ADT-like type classes

### ISSUE THREAD

**Issue by Lysxia** [sjoerdvisscher/one-liner#6]
It would be nice to refactor `ADT'`, `ADTNonEmpty'`, and `ADTRecord'`, so that, for example, we no longer need different `createA` and `createA'`.
These classes differ only in the constraints on the profunctor `p`. There are a couple of ways to abstract over them. Do you have any preference or objection?

**Comment by sjoerdvisscher** [comment]
I could not find a way to refactor them together without affecting the user-facing API. If you find a nice way to merge them, I'd be happy to do that!

You'd still need different `createA` and `createA'`, because one requires `Alternative f` and the other `Applicative f`.

**Comment by Lysxia** [comment]
I suppose backwards compatibility reduces the possible outcomes a bit. Would it be acceptable to only maintain a relaxed form of backwards compatibility: some constraints may change, but every existing use site with concrete types should still typecheck?

Such changes may only affect users with intermediate polymorphic bindings, which I can imagine being made for convenience:

    genericArbitrary :: (ADTRecord t, Constraints t Arbitrary) => Gen t
    genericArbitrary = createA' (For :: For Arbitrary) arbitrary

but even these constraints can be made future-proof via a type constraint synonym.

**Comment by sjoerdvisscher** [comment]
Sure!
Op ma 3 apr. 2017 om 16:56 schreef Xia Li-yao <notifications@github.com>

**Comment by sjoerdvisscher** [comment]
I'll leave this open until someone proves that it is impossible to do this without making the user-facing API worse.
